In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "../data/processed/Attendance_Preprocessed_Final.csv"
)

df.head()

,Student_ID,Student_Name,Email,Aadhaar_Number,College_Name,Session_ID,Session_Date,Domain,Join_Time,Leave_Time,Attendance_Minutes,Attendance_Status
0,ST0001,Sai Reddy,student0001@gmail.com,'433218196001,VIT AP,SESSION_01,2026-01-05,Machine Learning,09:05,11:00,51,Present
1,ST0001,Sai Reddy,student0001@gmail.com,'433218196001,VIT AP,SESSION_02,2026-01-06,Machine Learning,10:23,11:00,56,Present
2,ST0001,Sai Reddy,student0001@gmail.com,'433218196001,VIT AP,SESSION_03,2026-01-07,Machine Learning,10:13,11:00,51,Present
3,ST0001,Sai Reddy,student0001@gmail.com,'433218196001,VIT AP,SESSION_04,2026-01-08,Machine Learning,09:25,11:00,56,Present
4,ST0001,Sai Reddy,student0001@gmail.com,'433218196001,VIT AP,SESSION_05,2026-01-09,Machine Learning,09:30,11:00,59,Present

In [3]:
student_summary = (
    df.groupby('Student_ID')
      .agg(
          Student_Name=('Student_Name', 'first'),
          College_Name=('College_Name', 'first'),
          Total_Sessions=('Session_ID', 'count'),
          Sessions_Attended=(
              'Attendance_Status',
              lambda x: (x == 'Present').sum()
          ),
          Average_Attendance_Minutes=(
              'Attendance_Minutes',
              'mean'
          )
      )
      .reset_index()
)

In [4]:
student_summary['Attendance_Percentage'] = (
    student_summary['Sessions_Attended']
    /
    student_summary['Total_Sessions']
) * 100

In [5]:
student_summary['Certified'] = np.where(
    student_summary['Attendance_Percentage'] >= 80,
    1,
    0
)

In [6]:
student_summary.head()

,Student_ID,Student_Name,College_Name,Total_Sessions,Sessions_Attended,Average_Attendance_Minutes,Attendance_Percentage,Certified
0,ST0001,Sai Reddy,VIT AP,40,37,48.700,92.5,1
1,ST0002,Rohit Gupta,Narasaraopeta Engg,40,30,40.975,75.0,0
2,ST0003,Harsha Kumar,VNR VJIET,40,28,37.375,70.0,0
3,ST0004,Praveen Gupta,Gudlavalleru Engg,40,33,43.475,82.5,1
4,ST0005,Varun Patel,Andhra Loyola,40,27,35.900,67.5,0

In [7]:
student_summary.to_csv(
    "../data/processed/Student_Attendance_Summary.csv",
    index=False
)

print("Feature Engineering Completed")

Feature Engineering Completed